language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run build
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
github_token: $GITHUB_TOKEN  # Set this in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master